apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::840167699114:role/eksctl-my-eks-cluster-nodegroup-my-NodeInstanceRole-txUOKYhOesEQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::840167699114:user/janaka
      username: janaka
      groups:
        - system:masters
     
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-20T22:01:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1162"
  uid: 7e9b9644-d3f0-4210-800e-b4669e006a1f
